//VALIDATIONS
export { CannotBeBlank } from './CannotBeBlank.validation'
export { CannotContainNumbers } from './CannotContainNumbers.validation'
export { CannotContainSpecialCharacters } from './CannotContainSpecialCharacters.validation'
export { CannotHaveMoreThanXCharacters } from './CannotHaveMoreThanXCharacters.validation'
export { CannotStartWithZero } from './CannotStartWithZero.validation'
export { IsPositiveInteger } from './IsPositiveInteger.validation'
export { IsValidColor } from './IsValidColor.validation'
export { IsValidDate } from './IsValidDate.validation'
export { IsValidEmail } from './IsValidEmail.validation'
export { IsValidNumber } from './IsValidNumber.validation'
export { IsValidPhoneNumberBR } from './IsValidPhoneNumberBR.validation'
export { IsValidSlackChannel } from './IsValidSlackChannel.validation'
export { IsValidUrl } from './IsValidUrl.validation'
export { MustBeContainedInEnum } from './MustBeContainedInEnum.validation'
export { MustContainOnlyNumbers } from './MustContainOnlyNumbers.validation'
export { MustEndWithAlphaNumeric } from './MustEndWithAlphaNumeric.validation'
export { MustHaveAtLeastXCharacters } from './MustHaveAtLeastXCharacters.validation'
export { MustHaveOnlyOneWord } from './MustHaveOnlyOneWord.validation'
export { MustHaveTheSameStructureThan } from './MustHaveTheSameStructureThan.validation'
export { MustStartWithAlphaNumeric } from './MustStartWithAlphaNumeric.validation'
export { RegexMatch } from './RegexMatch.validation'



