name: smart-value-objects

on:
  push:
    branches: [ main ]
    paths:
      - 'package.json'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Publish package to NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          echo "Enter OTP:"
          read OTP
          npm publish --otp $OTP
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}