name: release

on: 
  push

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on:
      ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18'
      - run: npm install
      - run: npm ci
      - run: npm test
      - run: npm run build
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}